openapi: 3.0.0
info:
  title: NSW Crime Data API
  description: Provides historical and recent crime data for NSW suburbs using statistics from the NSW BOCSAR open data website.
  version: 1.0.0
servers:
  - url: https://api.yourdomain.com
    description: Production Server
paths:
  /data/collect:
    post:
      summary: Triggers crime data collection and processing
      description: Fetches the latest crime statistics from the NSW BOCSAR website, validates metadata, and updates the database if changes are detected.
      operationId: collectCrimeData
      responses:
        "200":
          description: Data collection and processing completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Crime data collection and processing completed successfully."
        "304":
          description: No new updates available, skipping processing.
          content:
            apllication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No updates detected. Skipping data processing."
        "500":
          description: Internal server error
  /crime/suburb/{name}:
    get:
      summary: Retrieve crime statistics for a given suburb
      description: Returns crime statistics for the requested suburb based on record ofences.
      operationId: getCrimeBySuburb
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the suburb (case-insensitive)
          schema:
            type: string
            example: "Kensington"
      responses:
        "200":
          description: Crime data for the requested suburb
          content:
            application/json:
              schema:
                type: object
                properties:
                  suburb:
                    type: string
                    example: "Kensington"
                  numCrimes:
                    type: integer
                    example: 500
                  crime:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        numOffences:
                          type: integer
                          example: 250
                        subCrimeType:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              numOffences:
                                type: integer
                                example: 100
        "404":
          description: Suburb not found in the dataset.
          content:
            application/json:
              schema:
                type: object
                properties:
                  suburb:
                    type: string
                    example: ""
                  numCrimes:
                    type: integer
                    example: 0
                  crime:
                    type: object
                    example: {}
        "500":
          description: Internal server error
  /crime/trends/{suburb}:
    get:
      summary: Retrieve crime trends for a given suburb
      description: Returns historical crime trends over the last 10 years.
      operationId: getCrimeTrends
      parameters:
        - name: suburb
          in: path
          required: true
          description: Name of the suburb (case-insensitive)
          schema:
            type: string
            example: "Kensington"
        responses:
          "200":
            description: Crime trends for the requested suburb
            contenet:
              application/json:
                schema:
                  type: object
                  properties:
                    suburb:
                      type: string
                      example: "Kenington"
                    crime:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          SubCrimeType:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                trendSlope:
                                  type: number
                                  example: -0.5
                                trendPercentage:
                                  type: number
                                  example: -12.5
                                movingAvg:
                                  type: number
                                  example: 45
                                trendCategory:
                                  type: string
                                  example: "Decreasing"
          "404":
            description: Suburb not found in the dataset.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    suburb:
                      type: string
                      example: ""
                    crime:
                      type: object
                      example: {}
          "500":
            description: Internal server error









