openapi: 3.0.0
info:
  title: Extreme Weather Data API
  description: Provides historical and real-time extreme weather data based on NSW natural disaster declarations.
  version: 1.0.0

servers:
  - url: https://api.yourdomain.com
    description: Production Server

paths:
  /data/collect:
    post:
      summary: Triggers data collection and processing
      description: Scrapes the latest NSW natural disaster declarations, aggregates it with pre-stored data, and processes it for analysis.
      operationId: collectData
      responses:
        "200":
          description: Data collection and processing completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Data collection and processing completed successfully."
        "500":
          description: Internal server error

  /data/suburb/{name}:
    get:
      summary: Retrieve extreme weather trends for a given suburb
      description: Returns disaster occurrence data, a livability score, and relevant natural disasters for the requested suburb.
      operationId: getSuburbData
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the suburb (case-insensitive)
          schema:
            type: string
            example: "Gunnedah"
      responses:
        "200":
          description: Extreme weather trends for the requested suburb
          content:
            application/json:
              schema:
                type: object
                properties:
                  suburb:
                    type: string
                    example: "Gunnedah"
                  score:
                    type: number
                    format: float
                    example: 3.27
                  occurrences:
                    type: integer
                    example: 3
                  disaster_names:
                    type: array
                    items:
                      type: string
                    example:
                      - "NSW Flooding from 14 September 2022 onwards"
                      - "Southern and Central West NSW Flooding from 4 August 2022 onwards"
                      - "NSW severe weather and flooding 9 November 2021 onwards"
        "404":
          description: Suburb not found
        "500":
          description: Internal server error
