openapi: 3.0.0
info:
  title: Family Census Data API
  description: API for retrieving family composition and population data for a given suburb.
  version: 1.0.0

servers:
  - url: https://tzeks84nk6.execute-api.ap-southeast-2.amazonaws.com/test/family/
    description: Production Server

paths:
  /family/{suburb}:
    get:
      summary: Get family composition data for a given suburb
      parameters:
        - name: suburb
          in: path
          required: true
          schema:
            type: string
          description: The suburb for which family composition data is requested.
      responses:
        200:
          description: Successful response with family composition data
          content:
            application/json:
              schema:
                type: object
                properties:
                  suburb:
                    type: string
                  total_families:
                    type: string
                  couple_family_with_no_children:
                    type: string
                  couple_family_with_children_under_15:
                    type: string
                  couple_family_with_children_over_15:
                    type: string
                  total_couple_families:
                    type: string
                  one_parent_with_children_under_15:
                    type: string
                  one_parent_with_children_over_15:
                    type: string
                  total_one_parent_families:
                    type: string
                  other_family:
                    type: string
              example:
                suburb: "Strathfield"
                total_families: "11,545"
                couple_family_with_no_children: "4,258"
                couple_family_with_children_under_15: "3,573"
                couple_family_with_children_over_15: "1,953"
                total_couple_families: "5,528"
                one_parent_with_children_under_15: "469"
                one_parent_with_children_over_15: "931"
                total_one_parent_families: "1,399"
                other_family: "360"
        400:
          description: Bad Request – e.g. suburb not provided or invalid format.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "No suburb provided in event"
        404:
          description: Not Found – The provided suburb was not found in the data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Suburb not found"
        500:
          description: Internal Server Error – An unexpected error occurred.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error processing the request: [detailed error message]"

  /family/population/{suburb}:
    get:
      summary: Get population data for a given suburb
      parameters:
        - name: suburb
          in: path
          required: true
          schema:
            type: string
          description: The suburb for which population data is requested.
      responses:
        200:
          description: Successful response with population data
          content:
            application/json:
              schema:
                type: object
                properties:
                  suburb:
                    type: string
                  total_population:
                    type: string
                  male:
                    type: string
                  female:
                    type: string
              example:
                suburb: "Strathfield"
                total_population: "45,593"
                male: "23,365"
                female: "22,229"
        400:
          description: Bad Request – e.g. suburb not provided or invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "No suburb provided in event"
        404:
          description: Not Found – The suburb was not found in the data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Suburb not found"
        500:
          description: Internal Server Error – An unexpected error occurred.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Error processing the request: [detailed error message]"