name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12" # Update as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
          pip install pandas

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=5 $(git ls-files '*.py')

      - name: Deploy to test environment
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh test

      - name: Run tests
        run: |
          chmod +x ./runtests.sh
          ./runtests.sh

      - name: Deploy to dev environment
        if: ${{ success() }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh dev
